// Code generated by github.com/tizz98/results; DO NOT EDIT.
package results

import (
	"context"
	"fmt"
)

type StringResult struct {
	value *string
	err   error
}

// IsOk returns true when the result contains a non-nil result with no error
func (r StringResult) IsOk() bool {
	return r.err == nil
}

// IsErr returns true when the result contains a non-nil error
func (r StringResult) IsErr() bool {
	return r.err != nil
}

// Unwrap panics if the result contains an error, otherwise it returns the value
func (r StringResult) Unwrap() string {
	if r.IsErr() {
		panic("cannot unwrap StringResult, it is an error")
	}
	return *r.value
}

// UnwrapOr returns the value if there is not an error, otherwise the specified value is returned
func (r StringResult) UnwrapOr(v string) string {
	if r.IsOk() {
		return r.Unwrap()
	}
	return v
}

// UnwrapOrElse returns the value if there is not an error, otherwise the function is called and the result is returned
func (r StringResult) UnwrapOrElse(fn func(err error) string) string {
	if r.IsOk() {
		return r.Unwrap()
	}
	return fn(r.err)
}

// Ok sets the result to a successful result with the provided value.
// This will panic if the result has already been set to successful or an error.
func (r *StringResult) Ok(v string) {
	r.checkAbilityToSet()
	r.value = &v
}

// Err sets the result to an error result with the provided error.
// This will panic if the result has already been set to successful or an error.
func (r *StringResult) Err(err error) {
	r.checkAbilityToSet()
	r.err = err
}

// GetError returns the error of the result. It may be nil, so check with StringResult.IsErr() first.
func (r StringResult) GetErr() error {
	return r.err
}

// Tup returns a tuple of (string, error) with "" being returned for string if there is an error
func (r StringResult) Tup() (string, error) {
	return r.UnwrapOr(""), r.err
}

// Set is a shortcut to checking the value of an error before setting the result.
// If there is an error, StringResult.Err(err) will be called, otherwise StringResult.Ok(v) will be called.
func (r *StringResult) Set(v string, err error) {
	if err != nil {
		r.Err(err)
		return
	}

	r.Ok(v)
}

func (r StringResult) checkAbilityToSet() {
	if r.isSet() {
		panic("StringResult is already set, cannot set again")
	}
}

func (r StringResult) isSet() bool {
	return r.value != nil || r.err != nil
}

func ContextWithString(ctx context.Context, key interface{}, v string) context.Context {
	return context.WithValue(ctx, key, v)
}

func StringFromContext(ctx context.Context, key interface{}) (result StringResult) {
	if v, ok := ctx.Value(key).(string); !ok {
		result.Err(fmt.Errorf("%#v not found in context", key))
	} else {
		result.Ok(v)
	}
	return
}
